<a href="https://colab.research.google.com/github/ShrutiPandey27/machine_learning_practice/blob/main/K_fold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# k fold cross validation

In [6]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [2]:
iris=load_iris()
x=iris.data
y=iris.target

In [3]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

#Logistic Regression

In [4]:
lr_score=cross_val_score(LogisticRegression(),x,y)
lr_score

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
np.average(lr_score)

0.9733333333333334

#Decision Tree

In [8]:
dt_score=cross_val_score(DecisionTreeClassifier(),x,y)
dt_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [9]:
np.average(dt_score)

0.9666666666666668

#Support Vector Machine

In [10]:
svm_score=cross_val_score(SVC(),x,y)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
np.average(svm_score)

0.9666666666666666

**henceforth** *so far logistic regression is giving good performance.*

# k fold 2nd approach

In [12]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)