<a href="https://colab.research.google.com/github/ShrutiPandey27/machine_learning_practice/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KNN->K-Nearest Neighbor algorithm
 
* it is supervised machiene learning algorithm
* simple algorithm and works over similarities.
* store complete data as training data
* can be used for classification and regression.
*  non parametric :it doesn't make any assumption 
* lazy learner:there is no training phase.it memorizes the things when it gets new datasets/new points and it calculates label and classifies based on more similarities.
* used for large data
* finding k value is difficult.(generally done by hit and trial method)



suppose we have 2 categories:A,B

**steps**:


1.find out k i.e., no. of neighbours


2.calculate euclidean(few other distance are also there) instance.


3.find the neighbours (maybe 5 or 10)with minimum distance.

4.compare those neighbours with both categories.

5.select category that has more number of neighbour.

In [1]:
#k fold cross validation used to find out which algorithm is best fit for our dataset based on the performance.

import sklearn
import pandas as pd
import numpy as np


In [2]:
from sklearn.datasets import load_iris
iris=load_iris()
iris.keys()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
df=pd.DataFrame(iris['data'])
print(df.head())

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2


In [4]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [5]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
x=df
y=iris['target']

In [7]:
#splitting data 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train) #feature data is xtrain and target data is ytrain


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [9]:
#prediction and accuracy
x_new=np.array([[5,2.5,2,5.5]])
prediction=knn.predict(x_new)
prediction

array([1])

In [10]:
iris['target_names'][prediction]

array(['versicolor'], dtype='<U10')

In [12]:
#accuracy using metrics
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred=knn.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [13]:
print(accuracy_score(y_test,y_pred))
#to find wrong prediction 1-accuracy_score

0.9736842105263158
